spring.application.name=week3 homework
spring.datasource.url=jdbc:mysql://localhost:3306/workspace?useSSL=false
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=create
